version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=watchnotify
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - MAIL_USERNAME=${MAIL_USERNAME:-your-email@gmail.com}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-your-app-password}
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    depends_on:
      - postgres
    networks:
      - watch-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=watchnotify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - watch-network

volumes:
  postgres_data:

networks:
  watch-network:
    driver: bridge
